name: Test .NET 10 App

on:
    push: 
        branches: ["main"]

jobs:
    test:
        runs-on: windows-latest

        steps:
          - name: Check out the code
            uses: actions/checkout@v4

          - name: Install .NET Core
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 10.0.x
                cache: true 
            
          - name: Restore API
            run: dotnet restore OpenERP.API/OpenERP.API.csproj
            
          - name: Restore Tests
            run: dotnet restore OpenERP.Tests/OpenERP.Tests.csproj

          - name: Run Test
            run: dotnet test OpenERP.Tests